# Generated by Django 4.2.6 on 2023-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_eventusers_eventuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
